name: Song Jaehak
descraiption:
url: http://astralhpi.github.io
mail: master@hpi.cc
copyright: Â© 2014 Song Jaehak
markdown: redcarpet
pygments: true
encoding: utf-8
timezone: Asia/Seoul
paginate: 5
paginate_path: "blog/page:num"